In [1]:
import numpy as np
import pandas as pd

In [4]:
df_data = pd.read_csv("../data/fce_txt/all_converted.csv")

In [5]:
df_data

,incorrect,correct,error
0,Dear Helen.,"Dear Helen,","{'tag': 'RP', 'incorrect': '.', 'correct': ','..."
1,I have received your letter which is make me h...,"I have received your letter, which makes me h...","{'tag': 'MP', 'incorrect': '', 'correct': ',',..."
2,I have received your letter which is make me h...,"I have received your letter, which makes me h...","{'tag': 'UV', 'incorrect': 'is', 'correct': ''..."
3,I have received your letter which is make me h...,"I have received your letter, which makes me h...","{'tag': 'AGV', 'incorrect': 'make', 'correct':..."
4,I have received your letter which is make me h...,"I have received your letter, which makes me h...","{'tag': 'MT', 'incorrect': 'The', 'correct': '..."
...,...,...,...
44517,You have been presented some causes why shopp...,You have been presented with some reasons why ...,"{'tag': 'MT', 'incorrect': '', 'correct': 'wit..."
44518,You have been presented some causes why shopp...,You have been presented with some reasons why ...,"{'tag': 'RN', 'incorrect': 'causes', 'correct'..."
44519,You have been presented some causes why shopp...,You have been presented with some reasons why ...,"{'tag': 'R', 'incorrect': 'behaviour to make m..."
44520,You have been presented some causes why shopp...,You have been presented with some reasons why ...,"{'tag': 'RV', 'incorrect': 'act', 'correct': '..."
44521,You have been presented some causes why shopp...,You have been presented with some reasons why ...,"{'tag': 'RT', 'incorrect': 'as', 'correct': 'l..."

In [9]:
df_error_cat = pd.read_csv("error_categories.csv")

In [10]:
df_error_cat

,Error Code,Level 1 Category,Level 2 Category,Level 3 Category,Category Code,Frequency (as per image from google drive)
0,AG,Agreement,Misselection,Grammar,GM,1645
1,AGA,Agreement,Misselection,Grammar,GM,11537
2,AGD,Agreement,Misselection,Grammar,GM,8813
3,AGN,Agreement,Misselection,Grammar,GM,35605
4,AGQ,Agreement,Misselection,Grammar,GM,1427
...,...,...,...,...,...,...
71,UT,content-word,omission,lexis,LX,56246
72,UV,function word,omission,lexis,LX,24002
73,UY,function word,omission,lexis,LX,16998
74,W,word order,misordering,Grammar,GM,76586
75,X,negation,NaN,grammar,GM,4180

In [13]:
error_map = dict(zip(df_error_cat["Error Code"],df_error_cat["Category Code"]))
error_map

{'AG': 'GM',
 'AGA': 'GM',
 'AGD': 'GM',
 'AGN': 'GM',
 'AGQ': 'GM',
 'AGV': 'GM',
 'AS': 'GM',
 'CD': 'GM',
 'CE': 'DS',
 'CL': 'SM',
 'CN': 'GM',
 'CQ': 'GM',
 'DA': 'GM',
 'DC': 'GM',
 'DD': 'GM',
 'DI': 'GM',
 'DJ': 'GM',
 'DN': 'GM',
 'DQ': 'GM',
 'DT': 'GM',
 'DV': 'GM',
 'DY': 'GM',
 'FA': 'GM',
 'FD': 'GM',
 'FJ': 'GM',
 'FN': 'GM',
 'FQ': 'GM',
 'FV': 'GM',
 'FY': 'GM',
 'IA': 'GM',
 'ID': 'SM',
 'IJ': 'GM',
 'IN': 'GM',
 'IQ': 'GM',
 'IV': 'GM',
 'IY': 'GM',
 'L': 'DS',
 'M': 'LX',
 'MA': 'LX',
 'MC': 'LX',
 'MD': 'LX',
 'MJ': 'LX',
 'MN': 'LX',
 'MP': 'OT',
 'MQ': 'LX',
 'MT': 'LX',
 'MV': 'LX',
 'MY': 'LX',
 'R': 'LX',
 'RA': 'LX',
 'RC': 'LX',
 'RD': 'LX',
 'RJ': 'LX',
 'RN': 'LX',
 'RP': 'LX',
 'RQ': 'LX',
 'RT': 'LX',
 'RV': 'LX',
 'RY': 'LX',
 'S': 'OT',
 'SA': 'OT',
 'SX': 'OT',
 'TV': 'GM',
 'U': 'LX',
 'UA': 'LX',
 'UC': 'LX',
 'UD': 'LX',
 'UJ': 'LX',
 'UN': 'LX',
 'UP': 'OT',
 'UQ': 'LX',
 'UT': 'LX',
 'UV': 'LX',
 'UY': 'LX',
 'W': 'GM',
 'X': 'GM'}

In [29]:
df_data['error']

ValueError: dictionary update sequence element #0 has length 1; 2 is required

In [ ]:
df_data.loc[df['error']]