In [1]:
import numpy as np
import pandas as pd

In [30]:
df_data = pd.read_csv("../data/fce_txt/all_converted.csv")

In [31]:
df_data

,incorrect,correct,error_tag,inc_word,cor_word,start_off,end_off
0,Dear Helen.,"Dear Helen,",RP,.,",",10,['end_off']
1,I have received your letter which is make me h...,"I have received your letter, which makes me h...",MP,NaN,",",27,['end_off']
2,I have received your letter which is make me h...,"I have received your letter, which makes me h...",UV,is,NaN,34,['end_off']
3,I have received your letter which is make me h...,"I have received your letter, which makes me h...",AGV,make,makes,37,['end_off']
4,I have received your letter which is make me h...,"I have received your letter, which makes me h...",MT,The,For the,52,['end_off']
...,...,...,...,...,...,...,...
44517,You have been presented some causes why shopp...,You have been presented with some reasons why ...,MT,NaN,with,24,['end_off']
44518,You have been presented some causes why shopp...,You have been presented with some reasons why ...,RN,causes,reasons,30,['end_off']
44519,You have been presented some causes why shopp...,You have been presented with some reasons why ...,R,behaviour to make more fun of it,making it more fun,93,['end_off']
44520,You have been presented some causes why shopp...,You have been presented with some reasons why ...,RV,act,behave,182,['end_off']
44521,You have been presented some causes why shopp...,You have been presented with some reasons why ...,RT,as,like,186,['end_off']

In [32]:
df_error_cat = pd.read_csv("error_categories.csv")

In [33]:
df_error_cat

,Error Code,Level 1 Category,Level 2 Category,Level 3 Category,Category Code,Frequency (as per image from google drive)
0,AG,Agreement,Misselection,Grammar,GM,1645
1,AGA,Agreement,Misselection,Grammar,GM,11537
2,AGD,Agreement,Misselection,Grammar,GM,8813
3,AGN,Agreement,Misselection,Grammar,GM,35605
4,AGQ,Agreement,Misselection,Grammar,GM,1427
...,...,...,...,...,...,...
71,UT,content-word,omission,lexis,LX,56246
72,UV,function word,omission,lexis,LX,24002
73,UY,function word,omission,lexis,LX,16998
74,W,word order,misordering,Grammar,GM,76586
75,X,negation,NaN,grammar,GM,4180

In [38]:
error_map = dict(zip(df_error_cat["Error Code"],df_error_cat["Category Code"]))

'GM'

In [41]:
def map_errors(row, error_map): 
    return error_map[row['error_tag']]

In [45]:
df_data['err_type'] = df_data.apply (lambda row: map_errors(row, error_map), axis=1)

In [46]:
df_data

,incorrect,correct,error_tag,inc_word,cor_word,start_off,end_off,err_type
0,Dear Helen.,"Dear Helen,",RP,.,",",10,['end_off'],LX
1,I have received your letter which is make me h...,"I have received your letter, which makes me h...",MP,NaN,",",27,['end_off'],OT
2,I have received your letter which is make me h...,"I have received your letter, which makes me h...",UV,is,NaN,34,['end_off'],LX
3,I have received your letter which is make me h...,"I have received your letter, which makes me h...",AGV,make,makes,37,['end_off'],GM
4,I have received your letter which is make me h...,"I have received your letter, which makes me h...",MT,The,For the,52,['end_off'],LX
...,...,...,...,...,...,...,...,...
44517,You have been presented some causes why shopp...,You have been presented with some reasons why ...,MT,NaN,with,24,['end_off'],LX
44518,You have been presented some causes why shopp...,You have been presented with some reasons why ...,RN,causes,reasons,30,['end_off'],LX
44519,You have been presented some causes why shopp...,You have been presented with some reasons why ...,R,behaviour to make more fun of it,making it more fun,93,['end_off'],LX
44520,You have been presented some causes why shopp...,You have been presented with some reasons why ...,RV,act,behave,182,['end_off'],LX
44521,You have been presented some causes why shopp...,You have been presented with some reasons why ...,RT,as,like,186,['end_off'],LX

In [47]:
df_data.to_csv("categorized_data.csv", header = True, index=False)